title: "Mobile Development Tutorials"
email: theouras058@gmail.com
timezone: UTC
baseurl: "/mobile-development-training"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: thelouras
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-96540683-2

# Authors
authors:
  thelouras:
    name: Kostas
    display_name: Thelouras
    avatar: 'assets/images/sal.png'
    email: thelouras058@gmail.com
    web: https://www.thelouras.gr
    twitter: https://twitter.com/ThelourasK
    description: "Mobile Tech Lead @Threenitas"
  john:
    name: Test
    display_name: Test
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/mobile_brain_games/
  facebook: 
  twitter: https://twitter.com/mobbraingames

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
